language: ruby
bundler_args: --without development
before_script:
   - mysql -e 'CREATE DATABASE datainsight_insidegov_test;'
before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -qq wbritish
   - cp config/databases.travis.yml config/databases.yml
script:
 - RACK_ENV=test bundle exec rake db:migrate
 - RACK_ENV=test bundle exec rake spec
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
matrix:
  allow_failures:
    - rvm: 2.0.0
